# ===================================================================
# ==                 1. 执行配置 (Execution)                       ==
# ===================================================================
# 控制程序如何运行，处理哪些数据
execution:
  # 在此指定本次运行要评估的数据集名称，仅用于指示和评估
  datasetToRun: "3DMatch"

  # 所有文件路径都集中在这里
  paths:
    cloudSrc: "../test_data/src.ply"
    cloudTgt: "../test_data/tgt.ply"
    cloudSrcKpt: "../test_data/src_kpts.pcd"
    cloudTgtKpt: "../test_data/tgt_kpts.pcd"
    correspondences: "../test_data/corr.txt"
    corresIndex: "../test_data/corr_ind.txt"
#    output: "../test_data/output"
    output: "../test_data/output2"

  # 系统控制
  system:
    desiredThreads: -1
    logLevel: "DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL
    noLogFile: false  # if true, the program will not produce the log file

  # 未使用，仍在开发中
  inDevelopment:
    lowInlierRatio: false # Not used
    addOverlap: false     # Not used
    useTopK: false        # Not used

# ===================================================================
# ==                 2. 核心算法配置 (Algorithm)                   ==
# ===================================================================
# 这些参数直接影响算法的行为，且与任何特定数据集无关
algorithm:

  lidarNoiseModel:
    # Below are not used
    maxRange: 80.0          # in meters
    minRange: 0.0           # in meters
    verticalFOV: 30.0       # in degrees
    horizontalFOV: 360.0    # in degrees
    verticalRes: 0.4        # in degrees
    horizontalRes: 0.35     # in degrees
    numScanLines: 64        # number of scan lines, e.g., 16, 32, 64
    # Below are used
    varianceMode: "FIXED" # Options: "FIXED", "DYNAMIC"
    # Velodyne HDL 64 Lidar
    sigmaRho: 0.05          # in meters
    sigmaTheta: 0.2304      # in degrees (zenith)
    sigmaPhi: 0.09          # in degrees (azimuth)
    NSigma: 1               # n sigma for outlier rejection

  # 图构建参数
  graph:
    scoreFormula: "GAUSSIAN_KERNEL" # GAUSSIAN_KERNEL or QUADRATIC_FALLOFF
    secondOrderGraph: false

  clique:
    # Maximal clique search parameters
    maxTotalNum: 10000000
    maxIterations: 5
    maxSize: 15 # Should not be less than 3 + maxIterations
    # Clique filtering parameters
    maxLocalNum: 11 # 因为逻辑不一样，源码里面写的是>maxLocalNum，我们这里写的是==maxLocalNum

  hypothesis:
    maxEstimateNum: 2147483647  # INT_MAX
    instanceEqual: true
    localEvaluationMetric: "MAE"

  # 精炼与最终决策参数
  refinement:
    useIcp: false
    clusterInternalEvaluation: true

# ===================================================================
# ==                 3. 监控与日志 (Monitor)                       ==
# ===================================================================
monitor:
  enabled: true         # 关闭后：所有 enter/record/CSV/tee/树状摘要均不执行

  # 粒度：只记关键阶段，还是全量细节
  granularity: "ALL"   # 可选: "CORE" | "ALL"    [默认 CORE]

  # 阶段指标（写入 CSV 的 note 字段）
  metrics: "AUTO"       # 可选: "OFF" | "AUTO" | "ALL"
    # - OFF  : 不写任何指标（仅时间/内存）
    # - AUTO : evaluation.enabled==true 时写指标；否则不写
    # - ALL  : 无视 evaluation.enabled，所有阶段都写指标
  #   （你现在的需求建议用 AUTO）

  # 仅在 granularity=CORE 时生效：层级阈值
  coreDepth: 2          # 取“栈深≤2”的阶段作为关键阶段（可按需要调到1/3）

  # 命令行树状摘要（Time Tree）
  timeTree:
    enabled: true
    charset: "ascii"  # 可选: "unicode" | "ascii"
    showMemory: true
    showNotes: true     # 是否在每行尾部截断展示少量 note（metrics）
    maxDepth: -1        # -1 表示不限制

  summary:
    enabled: true   # 控制是否在启动时打印配置摘要

# ===================================================================
# ==                 4. 评估专用配置 (Evaluation)                  ==
# ===================================================================
# 所有仅用于评估和对比真值的参数都在这里
evaluation:
  # 真值文件路径 (GT)
  paths:
    groundTruthLabels: "../test_data/label.txt"
    groundTruthTransform: "../test_data/GTmat.txt"

  # 各个数据集的评估阈值
  datasets:
    "3DMatch":
      rotationErrorThreshold: 15.0        # 旋转误差阈值，单位：度
      translationErrorThreshold: 0.30     # 平移误差阈值，单位：米
      inlierThreshold: 0.1                # 内点评估阈值，单位：米
      clusteringAngleThreshold: 5.0       # 聚类角度阈值，单位：度（转换为弧度时 * PI/180）
      clusteringDistanceThreshold: 0.1    # 聚类距离阈值，与inlierEvaThresh相同、
      successRMSEThreshold: 0.2           # 成功配准的RMSE阈值
      # 可选：为该数据集预计算的分辨率，以加速批量处理
      # 如果注释掉或设为0，程序会自动计算
      meshResolution: 0.00605396          # 点云分辨率，单位：米

    "3DLoMatch":
      rotationErrorThreshold: 15.0
      translationErrorThreshold: 0.30
      inlierThreshold: 0.1
      clusteringAngleThreshold: 5.0
      clusteringDistanceThreshold: 0.1
      successRMSEThreshold: 0.2
      meshResolution: 0.00605396

    "KITTI":
      rotationErrorThreshold: 5.0
      translationErrorThreshold: 1.80
      inlierThreshold: 1.8
      clusteringAngleThreshold: 3.0
      clusteringDistanceThreshold: 1.8
      successRMSEThreshold: 0.2
      meshResolution: 0.09 # 示例值

    "U3M":
      # U3M的阈值是基于分辨率的乘数，而不是固定值
      # 上述这一点待定
      rotationErrorThreshold: 5.0
      translationErrorThreshold: 0.0
      inlierThresholdMultiplier: 5.0
      clusteringAngleThreshold: 3.0
      clusteringDistanceThresholdMultiplier: 5.0
      successRMSEThreshold: 0.2

    "ETH":
      rotationErrorThreshold: 15.0
      translationErrorThreshold: 30.0
      inlierThreshold: 0.1
      clusteringAngleThreshold: 5.0
      clusteringDistanceThreshold: 0.1
      successRMSEThreshold: 0.2
