# Scenes in each dataset
datasets:
  threeDMatch:
    - 7-scenes-redkitchen
    - sun3d-home_at-home_at_scan1_2013_jan_1
    - sun3d-home_md-home_md_scan9_2012_sep_30
    - sun3d-hotel_uc-scan3
    - sun3d-hotel_umd-maryland_hotel1
    - sun3d-hotel_umd-maryland_hotel3
    - sun3d-mit_76_studyroom-76-1studyroom2
    - sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika

  threeDlomatch:
    - 7-scenes-redkitchen_3dlomatch
    - sun3d-home_at-home_at_scan1_2013_jan_1_3dlomatch
    - sun3d-home_md-home_md_scan9_2012_sep_30_3dlomatch
    - sun3d-hotel_uc-scan3_3dlomatch
    - sun3d-hotel_umd-maryland_hotel1_3dlomatch
    - sun3d-hotel_umd-maryland_hotel3_3dlomatch
    - sun3d-mit_76_studyroom-76-1studyroom2_3dlomatch
    - sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika_3dlomatch

  ETH:
    - gazebo_summer
    - gazebo_winter
    - wood_autmn
    - wood_summer

  # 添加KITTI和U3M数据集的场景列表（如果有的话）
  KITTI:
    - sequence_00
    - sequence_01
    - sequence_02
    # 可根据实际KITTI数据集场景添加更多

  U3M:
    - scene_01
    - scene_02
    - scene_03
    # 可根据实际U3M数据集场景添加更多

